String desIntro =
    "A French descriptive essay, also known as an \"essai descriptif,\" is a type of essay that describes a person, place, object, or event in detail. The goal of this type of essay is to create a vivid picture in the reader's mind, using sensory details, figurative language, and vivid descriptions.\nThe structure of a French descriptive essay typically includes an introduction, a body, and a conclusion. The introduction should provide some background information about the topic and set the tone for the essay. The body should include detailed descriptions of the subject, using sensory details and figurative language to create a vivid image in the reader's mind. The conclusion should wrap up the essay and provide a final impression of the subject.\n\nSome of the most popular French descriptive essays include essays about famous landmarks, cities, natural wonders, and works of art. These types of essays allow the writer to explore their own reactions and perceptions of the subject, as well as convey information to the reader in a descriptive and engaging way.\nHere are some helpful tips for writing a French descriptive essay:\n1.  Choose a subject that is interesting to you and has a lot of descriptive potential.\n2. Use sensory details to create a vivid image in the reader's mind.\n3. Use figurative language, such as similes and metaphors, to enhance the descriptions.\n4. Use a variety of sentence structures to keep the reader engaged.\nUse transitions to move smoothly between different aspects of the subject.\n5. Edit and revise the essay for clarity, coherence, and style.\n\nIn terms of verb conjugations, it's important to use the appropriate tense for the descriptions being given. For example, if the essay is describing a past event or object, the verbs should be conjugated in the passé composé or imparfait. If the essay is describing a current or ongoing situation, the verbs should be conjugated in the present tense.\n\nHere are some examples of verb conjugations in a French descriptive essay:\n\nPassé Composé:\n\n La Tour Eiffel a été construite en 1889. (The Eiffel Tower was built in 1889.)\nJ'ai visité le Louvre l'année dernière. (I visited the Louvre last year.)\n\nImparfait:\nLe château était majestueux, avec des tours qui s'élevaient dans le ciel. (The castle was majestic, with towers that rose into the sky.)\nLes jardins étaient magnifiques, avec des fleurs de toutes les couleurs. (The gardens were beautiful, with flowers of all colors.)\n\n";

String desFooter =
    "In conclusion, a French descriptive essay is a great way to convey a detailed picture of a person, place, object, or event to the reader. By using sensory details, figurative language, and vivid descriptions, the writer can create an engaging and informative essay. Using the appropriate verb conjugations is also important in creating an accurate and effective descriptive essay.";

//sentence structure mmmmmmmmmmm
String structIntro =
    "French sentence structure follows a pattern of subject-verb-object (SVO) in declarative sentences, although there are exceptions to this rule. The basic structure of a French sentence can be broken down into the following components: \n\n1. Subject: The person, thing, or idea that performs the action in the sentence. In French, the subject comes before the verb. For example, \"Le chat mange une souris\" (The cat eats a mouse).\n 2. Verb: The action or state of being that the subject performs. In French, the verb usually comes after the subject. For example, \"Le chat mange une souris\" (The cat eats a mouse).\n 3.  Object: The person, thing, or idea that is affected by the action of the verb. In French, the object usually comes after the verb. For example, \"Le chat mange une souris\" (The cat eats a mouse).\n 4.  Adverb: A word that modifies the meaning of the verb, adjective, or other adverb in the sentence. In French, adverbs can appear in various places in the sentence. For example, \"Le chat mange rapidement une souris\" (The cat eats a mouse quickly).\n 5.  Adjective: A word that describes or modifies the noun or pronoun in the sentence. In French, adjectives usually come after the noun they modify. For example, \"Une souris grise\" (A gray mouse).\n\n Here's a table of some common French sentence structures: \n ";

String structFooter =
    "It's important to note that in French, the word order can be changed to emphasize certain parts of the sentence. For example, \"Une souris, le chat mange\" (A mouse, the cat eats) emphasizes the subject and object of the sentence.\n\nIn addition, French has a number of different sentence structures and connectors that can be used to link phrases and clauses. These include coordinating conjunctions (e.g. \"et\" for \"and\"), subordinating conjunctions (e.g. \"quand\" for \"when\"), and relative pronouns (e.g. \"qui\" for \"who\" or \"which\").\n\nIn conclusion, understanding French sentence structure is essential for effective communication in the language. By mastering the basic components and structures of a sentence, learners can construct grammatically correct and meaningful sentences in French.";
